flowchart LR
    StudyDesign((Study Designs)) --> AssignExposure{Did investigators assign exposure?}
    AssignExposure -->|No| Observational[Observational]
    AssignExposure -->|Yes| Experimental[Experimental]


    Observational --> Population[Population-based]
    Observational --> Individual[Individual-based]

    Population --> Ecological[Ecological]
    Ecological --> |Useful for| EcologicalUseful[Description of population-level characteristics]
    Ecological --> |Limitation| EcologicalLimitation[Characteristics are attributed to the whole group, not individuals]
    Ecological --> |Example| EcologicalExample[Correlation between air pollution levels and asthma rates in different cities]

    Individual --> TimeOutcome{When was the outcome determined?}
    TimeOutcome -->|Before the exposure| CaseControl[Case-Control]
    CaseControl --> CaseControlDesign[Design]
    CaseControlDesign --> Cases["Cases (with disease)"]
    Cases --> CasesExposed[Exposed]
    Cases --> CasesNotExposed[Non-Exposed]
    CaseControlDesign --> Controls["Controls (without disease)"]
    Controls --> ControlsExposed[Exposed]
    Controls --> ControlsNotExposed[Non-Exposed]
    CaseControl --> |Useful for| CaseControlUseful[Studying risk factors and etiologies of rare diseases]
    CaseControl --> |Limitation| CaseControlLimitation[Can suggest causality but cannot prove it]
    CaseControl --> |Limitation| CaseControlLimitation2[Cannot estimate prevalence of a disease in the population]
    CaseControl --> |Example| CaseControlExample[Association between smoking and lung cancer in a group of patients with lung cancer and a group without lung cancer]
    TimeOutcome --> |At the same time as the exposure| CrossSectional[Cross-Sectional]
    CrossSectional --> |Useful for| CrossSectionalUseful[Assessing prevalence of a disease in a population at a specific point in time]
    CrossSectional --> |Limitation| CrossSectionalLimitation[Cannot establish temporal relationship between exposure and outcome]
    CrossSectional --> |Example| CrossSectionalExample["Prevalence of hypertension (the outcome) in a sample of adults in a particular region at a single point in time. The researchers would measure blood pressure levels in each participant and gather information on other factors that could influence blood pressure, such as age, sex, weight, and lifestyle habits (exposure)".]
    TimeOutcome -->|After the exposure| Cohort[Cohort]
    Cohort --> CohortDesign[Design]
    CohortDesign --> Exposed[Exposed/Risk Factor Present]
    Exposed --> ExposedOutcome[Disease/outcome]
    Exposed --> ExposedNotOutcome[No disease/outcome]
    CohortDesign --> NonExposed[Non-Exposed/Risk Factor Absent]
    NonExposed --> NonExposedOutcome[Disease/outcome]
    NonExposed --> NonExposedNotOutcome[No disease/outcome]
    Cohort --> PastRecords{Past records are accurate and reliable?}
    PastRecords --> |No|CohortProspective[Prospective]
    PastRecords --> |Yes|CohortRetrospective[Retrospective]
    CohortProspective --> |Limitation| CohortProspectiveLimitation[Time-consuming and expensive]
    Cohort --> |Useful for| CohortUseful[Establishing temporal relationship between exposure and outcome]
    Cohort --> |Useful for| CohortUseful2[Suspected exposure is known and rare, and the incidence of the outcome is high in the exposed group]
    Cohort --> |Limitation| CohortLimitation[Can infer and interpret causality but cannot prove it]
    Cohort --> |Limitation| CohortLimitation2[Drop-outs]
    Cohort --> |Example| CohortExample["A study that follows a group of individuals over time to assess the relationship between their dietary habits (exposure) and the development of cardiovascular disease (outcome). The researchers would collect data on participants' diets at baseline and then track their health outcomes over several years."]


    Experimental --> ClinicalTrial[Clinical Trial]
    ClinicalTrial --> |Focus| ClinicalTrialFocus["Testing the efficacy and safety of interventions in a controlled environment (mainly sick patients)"]
    ClinicalTrial --> |Setting| ClinicalTrialSetting[Controlled environment, often in a hospital or clinic]
    ClinicalTrial --> RandomAllocation{Random allocation of participants to intervention or control group?}
    RandomAllocation --> |Yes| RandomizedControlledTrial[RCT]
    RandomAllocation --> |No| NonRandomizedTrial[Non-Randomized Trial]
    RandomizedControlledTrial --> Design[Design]
    Design --> ParallelGroup[Parallel Group]
    Design --> Crossover[Crossover]
    Design --> Factorial[Factorial]
    ParallelGroup --> |Description| ParallelGroupDescription[Participants are randomly assigned to one of two or more groups, and each group receives a different intervention or control condition. The outcomes are compared between the groups to determine the effectiveness of the interventions.]
    ParallelGroup --> ParallelGroupStructure[Structure]
    ParallelGroupStructure --> InterventionGroup[Intervention Group]
    ParallelGroupStructure --> ControlGroup[Control Group]
    Crossover --> |Description| CrossoverDescription[Participants receive multiple interventions in a specific order, with a washout period in between. Each participant serves as their own control, allowing for within-subject comparisons of the interventions.]
    Crossover --> CrossoverStructure[Structure]
    CrossoverStructure --> InterventionA[Intervention A]
    CrossoverStructure --> WashoutPeriod[Washout Period]
    CrossoverStructure --> InterventionB[Intervention B]
    Factorial --> |Description| FactorialDescription[Participants are assigned to multiple interventions simultaneously, allowing for the assessment of the effects of each intervention as well as their interactions.]
    Factorial --> FactorialStructure[Structure]
    FactorialStructure --> Intervention1[Intervention 1]
    FactorialStructure --> Intervention2[Intervention 2]
    FactorialStructure --> InteractionEffect[Interaction Effect]
    Experimental --> FieldTrial[Field Trial]
    FieldTrial --> |Focus| FieldTrialFocus[Testing preventative interventions among healthy individuals living in the community to see if it reduces their risk of developing a disease]
    FieldTrial --> |Setting| FieldTrialSetting[The participants' natural, day-to-day environments rather than institutions]
    FieldTrial --> |Example| FieldTrialExample[Assigning a vaccine or a nutritional supplement to individuals to measure infection rates later]
    Experimental --> CommunityTrial[Community Trial]
    CommunityTrial --> |Focus| CommunityTrialFocus[Evaluating massive public health interventions directed at a whole collective group, rather than individuals]
    CommunityTrial --> |Setting| CommunityTrialSetting[Geographic areas, towns, schools, or factories]
    CommunityTrial --> |Example| CommunityTrialExample[One city might receive an educational anti-smoking campaign or a water-treatment initiative, while a neighboring city acts as the untreated control]